import { cn } from "@/lib/utils";

const adminStyles: Record<string, string> = {
  "admin-workbench-shell": "grid min-h-dvh grid-cols-[18rem_minmax(0,1fr)] bg-[var(--paper)] text-[color:var(--ink)] max-[64rem]:grid-cols-1",
  "admin-workbench-main": "min-w-0",
  "admin-workbench-note": "flex items-center gap-[0.45rem] px-[clamp(1rem,3vw,2rem)] pt-4 text-[0.72rem] font-bold tracking-[0.08em] text-[color:var(--ink-soft)] uppercase [&_svg]:text-[color:var(--terracotta-dark)]",
  "admin-workbench-content": "min-h-[calc(100dvh_-_2.5rem)] p-[clamp(1.25rem,3vw,2.5rem)] max-[42rem]:px-4",
  "admin-sidebar": "sticky top-0 flex h-dvh flex-col gap-6 border-r border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_92%,white)] p-5 max-[64rem]:hidden",
  "admin-sidebar-brand": "inline-flex min-h-14 items-center gap-3 text-[color:var(--ink)] no-underline [&_strong]:block [&_strong]:text-[0.98rem] [&_strong]:leading-none [&_small]:mt-[0.28rem] [&_small]:block [&_small]:text-[0.68rem] [&_small]:font-bold [&_small]:tracking-[0.08em] [&_small]:text-[color:var(--ink-soft)] [&_small]:uppercase",
  "admin-nav-groups": "grid gap-5",
  "admin-nav-group-label": "mb-[0.45rem] mt-0 text-[0.68rem] font-extrabold tracking-[0.1em] text-[color:var(--ink-soft)] uppercase",
  "admin-nav-items": "grid gap-[0.3rem]",
  "admin-nav-link": "flex min-h-[2.85rem] items-center gap-[0.7rem] rounded-[var(--radius-sm)] border border-transparent px-[0.82rem] text-[0.9rem] font-bold text-[color:color-mix(in_srgb,var(--ink)_74%,var(--ink-soft))] no-underline transition-[background-color,border-color,color,transform] duration-[180ms] hover:border-[var(--line)] hover:bg-[color-mix(in_srgb,var(--paper)_75%,white)] hover:text-[color:var(--ink)] focus-visible:border-[var(--line)] focus-visible:bg-[color-mix(in_srgb,var(--paper)_75%,white)] data-[active=true]:border-[color-mix(in_srgb,var(--terracotta-dark)_42%,var(--line))] data-[active=true]:bg-[color-mix(in_srgb,var(--terracotta)_12%,var(--paper-raised))] data-[active=true]:text-[color:var(--terracotta-dark)]",
  "admin-sidebar-bottom": "mt-auto grid gap-[0.45rem] border-t border-[var(--line)] pt-4",
  "admin-logout-button": "inline-flex min-h-[2.85rem] items-center justify-center gap-[0.7rem] rounded-[var(--radius-sm)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper)_80%,white)] px-[0.82rem] text-[0.9rem] font-extrabold text-[color:var(--ink)] transition-[background-color,border-color,transform] duration-[180ms] hover:border-[color-mix(in_srgb,var(--terracotta-dark)_35%,var(--line))] hover:bg-[color-mix(in_srgb,var(--terracotta)_10%,var(--paper-raised))]",
  "admin-menu-button": "inline-flex size-[2.8rem] items-center justify-center rounded-[var(--radius-sm)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper)_80%,white)] text-[color:var(--ink)] transition-[background-color,border-color,transform] duration-[180ms] hover:border-[color-mix(in_srgb,var(--terracotta-dark)_35%,var(--line))] hover:bg-[color-mix(in_srgb,var(--terracotta)_10%,var(--paper-raised))]",
  "admin-icon-action": "inline-flex size-[2.8rem] items-center justify-center rounded-[var(--radius-sm)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper)_80%,white)] text-[color:var(--ink)] transition-[background-color,border-color,transform] duration-[180ms] hover:border-[color-mix(in_srgb,var(--terracotta-dark)_35%,var(--line))] hover:bg-[color-mix(in_srgb,var(--terracotta)_10%,var(--paper-raised))]",
  "admin-mobile-bar": "sticky top-0 z-[70] hidden items-center justify-between border-b border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_94%,white)] px-4 py-3 max-[64rem]:flex",
  "admin-mobile-drawer": "fixed inset-0 z-[80] grid justify-items-end bg-[color-mix(in_srgb,var(--ink)_32%,transparent)]",
  "admin-mobile-drawer-panel": "flex h-full w-[min(22rem,calc(100vw_-_2rem))] flex-col gap-5 bg-[var(--paper-raised)] p-4 shadow-[-24px_0_70px_color-mix(in_srgb,var(--ink)_18%,transparent)]",

  "admin-dashboard": "mx-auto max-w-[76rem]",
  "admin-dashboard-hero": "flex items-end justify-between gap-8 rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-[clamp(1.5rem,3vw,2.5rem)] max-[64rem]:flex-col max-[64rem]:items-start [&_h1]:mt-[0.45rem] [&_h1]:max-w-[47rem] [&_h1]:text-[clamp(2.4rem,5vw,5.3rem)] [&_h1]:leading-[0.98] [&_p:not(.admin-eyebrow)]:mt-4 [&_p:not(.admin-eyebrow)]:max-w-[39rem] [&_p:not(.admin-eyebrow)]:leading-[1.7] [&_p:not(.admin-eyebrow)]:text-[color:var(--ink-soft)]",
  "admin-dashboard-actions": "flex flex-wrap items-center gap-[0.7rem]",
  "admin-eyebrow": "m-0 text-xs font-extrabold tracking-[0.08em] text-[color:var(--terracotta-dark)] uppercase",
  "admin-primary-action": "inline-flex min-h-[2.8rem] items-center justify-center gap-[0.55rem] rounded-[var(--radius-sm)] bg-[var(--terracotta-dark)] px-4 text-[0.9rem] font-extrabold text-white no-underline transition hover:bg-[#8c2e21] disabled:cursor-not-allowed disabled:opacity-60",
  "admin-loading": "mt-4 flex items-center gap-[0.55rem] rounded-[var(--radius-sm)] p-4 text-[0.92rem] text-[color:var(--ink-soft)]",
  "admin-alert": "mt-4 flex items-center gap-[0.55rem] rounded-[var(--radius-sm)] border border-[color-mix(in_srgb,#b42318_28%,var(--line))] bg-[color-mix(in_srgb,#fddbd6_70%,var(--paper))] p-4 text-[0.92rem] text-[#8f1d14]",
  "admin-pipeline-panel": "mt-4 grid grid-cols-[minmax(12rem,0.8fr)_minmax(0,1.8fr)] gap-6 rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-[clamp(1.25rem,2.5vw,2rem)] max-[64rem]:grid-cols-1 [&_h2]:mt-[0.45rem] [&_h2]:leading-[0.98]",
  "admin-pipeline-list": "m-0 grid list-none grid-cols-4 gap-3 p-0 max-[64rem]:grid-cols-2 max-[42rem]:grid-cols-1",
  "admin-pipeline-item": "grid min-h-36 content-between rounded-[var(--radius-sm)] border border-[var(--line)] bg-[var(--paper)] p-4 [&_b]:text-[clamp(2rem,3vw,3rem)] [&_b]:leading-[0.9] [&_b]:text-[color:var(--ink)] [&_small]:mt-[0.22rem] [&_small]:block [&_small]:text-[color:var(--ink-soft)] [&_strong]:block [&_strong]:text-[color:var(--ink)]",
  "admin-pipeline-icon": "grid size-[2.35rem] place-items-center rounded-full bg-[color-mix(in_srgb,var(--terracotta)_12%,var(--paper-raised))] text-[color:var(--terracotta-dark)]",
  "admin-metric-grid": "mt-4 grid grid-cols-4 gap-[0.8rem] max-[64rem]:grid-cols-2 max-[42rem]:grid-cols-1",
  "admin-metric-card": "rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-[1.1rem] [&_p]:mb-[0.35rem] [&_p]:mt-[1.7rem] [&_p]:text-[0.8rem] [&_p]:font-extrabold [&_p]:text-[color:var(--ink-soft)] [&_strong]:text-[2.35rem] [&_strong]:leading-none [&_strong]:text-[color:var(--ink)] [&_svg]:text-[color:var(--terracotta-dark)]",
  "admin-system-grid": "mt-4 grid grid-cols-2 gap-4 max-[64rem]:grid-cols-1",
  "admin-system-card": "rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-5 [&_dd]:mt-1 [&_dd]:text-[1.7rem] [&_dd]:font-extrabold [&_dd]:text-[color:var(--ink)] [&_dl]:mt-6 [&_dl]:grid [&_dl]:grid-cols-2 [&_dl]:gap-3 max-[42rem]:[&_dl]:grid-cols-1 [&_dt]:text-[color:var(--ink-soft)] [&_p]:mt-6 [&_p]:text-[color:var(--ink-soft)] [&_small]:text-[color:var(--ink-soft)]",
  "admin-system-card-heading": "flex items-center justify-between gap-[0.55rem] font-extrabold text-[color:var(--ink)] [&_span]:flex [&_span]:items-center [&_span]:gap-[0.55rem] [&_strong]:text-[0.86rem] [&_strong]:text-[color:var(--ink-soft)] [&_strong[data-state=bad]]:text-[#a63328] [&_strong[data-state=good]]:text-[#28744c] [&_svg]:text-[color:var(--terracotta-dark)]",

  "studio-flow": "mx-auto max-w-[76rem]",
  "studio-hero": "flex items-end justify-between gap-8 rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-[clamp(1.5rem,3vw,2.5rem)] max-[64rem]:flex-col max-[64rem]:items-start [&_h1]:mt-[0.45rem] [&_h1]:max-w-[48rem] [&_h1]:text-[clamp(2.4rem,5vw,5.2rem)] [&_h1]:leading-[0.98] [&_p:not(.admin-eyebrow)]:mt-4 [&_p:not(.admin-eyebrow)]:max-w-[41rem] [&_p:not(.admin-eyebrow)]:leading-[1.7] [&_p:not(.admin-eyebrow)]:text-[color:var(--ink-soft)]",
  "studio-layout": "mt-4 grid grid-cols-[minmax(0,1fr)_minmax(17rem,0.34fr)] gap-4 max-[64rem]:grid-cols-1",
  "studio-panel": "rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-[clamp(1rem,2vw,1.5rem)]",
  "studio-tabs": "grid grid-cols-4 gap-2 max-[64rem]:grid-cols-1",
  "studio-tab": "flex min-h-[4.35rem] items-center gap-[0.65rem] rounded-[var(--radius-sm)] border border-[var(--line)] bg-[var(--paper)] p-[0.8rem] text-left text-[0.78rem] font-extrabold text-[color:var(--ink-soft)] data-[active=true]:border-[color-mix(in_srgb,var(--terracotta-dark)_46%,var(--line))] data-[active=true]:bg-[color-mix(in_srgb,var(--terracotta)_10%,var(--paper-raised))] data-[active=true]:text-[color:var(--ink)] [&_span]:grid [&_span]:size-[1.7rem] [&_span]:shrink-0 [&_span]:place-items-center [&_span]:rounded-full [&_span]:bg-[color-mix(in_srgb,var(--terracotta)_12%,var(--paper-raised))] [&_span]:text-xs [&_span]:text-[color:var(--terracotta-dark)]",
  "studio-stage": "min-h-[27rem] pt-[clamp(1.25rem,3vw,2.5rem)] [&_h2]:m-0 [&_h2]:text-[clamp(2rem,4vw,4rem)] [&_h2]:leading-[0.98] [&_h2]:text-[color:var(--ink)] [&_h3]:m-0 [&_h3]:text-[1.05rem] [&_h3]:text-[color:var(--ink)] [&_p]:mt-[0.85rem] [&_p]:max-w-[41rem] [&_p]:leading-[1.65] [&_p]:text-[color:var(--ink-soft)] [&_label]:mt-5 [&_label]:grid [&_label]:gap-[0.55rem] [&_label]:text-[0.82rem] [&_label]:font-extrabold [&_label]:text-[color:var(--ink)]",
  "studio-input": "min-h-[2.9rem] w-full rounded-[var(--radius-sm)] border border-[var(--line)] bg-[var(--paper)] px-[0.9rem] text-[0.92rem] text-[color:var(--ink)] outline-none transition-[background-color,border-color] duration-[180ms] focus:border-[color-mix(in_srgb,var(--terracotta-dark)_48%,var(--line))] focus:bg-[color-mix(in_srgb,var(--paper)_80%,white)]",
  "studio-field-grid": "mt-4 grid grid-cols-3 gap-[0.85rem] max-[64rem]:grid-cols-1",
  "studio-output-grid": "mt-4 grid grid-cols-2 gap-[0.85rem] max-[64rem]:grid-cols-1",
  "studio-template-list": "mt-4 grid grid-cols-2 gap-[0.85rem] max-[64rem]:grid-cols-1",
  "studio-checkbox-card": "grid min-h-[5.2rem] content-start rounded-[var(--radius-sm)] border border-[var(--line)] bg-[var(--paper)] p-4 [&_input]:size-4 [&_small]:mt-1 [&_small]:block [&_small]:leading-[1.45] [&_small]:text-[color:var(--ink-soft)] [&_span]:block",
  "studio-template-panel": "mt-5 rounded-[var(--radius-sm)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper)_75%,white)] p-4",
  "studio-template-heading": "flex items-center justify-between gap-4 [&_a]:text-[0.85rem] [&_a]:font-extrabold [&_a]:text-[color:var(--terracotta-dark)]",
  "studio-warning": "text-[#9f2f24]",
  "studio-actions": "flex items-center justify-end gap-[0.7rem] border-t border-[var(--line)] pt-4",
  "studio-review": "mt-4 rounded-[var(--radius-sm)] border border-[var(--line)] bg-[var(--paper)] p-4 [&_dl]:m-0 [&_dl]:grid [&_dl]:grid-cols-2 [&_dl]:gap-3 max-[64rem]:[&_dl]:grid-cols-1 [&_div]:border-b [&_div]:border-[var(--line)] [&_div]:py-3 [&_dt]:text-[0.78rem] [&_dt]:font-extrabold [&_dt]:text-[color:var(--ink-soft)] [&_dd]:mt-1 [&_dd]:font-extrabold [&_dd]:text-[color:var(--ink)]",
  "studio-success": "mt-4 flex items-center justify-between gap-4 rounded-[var(--radius-sm)] border border-[color-mix(in_srgb,#2f8a59_26%,var(--line))] bg-[color-mix(in_srgb,#dff7e8_72%,var(--paper))] p-4 font-extrabold text-[#28744c] [&_a]:text-[0.85rem] [&_a]:font-extrabold [&_a]:text-[color:var(--terracotta-dark)] [&_span]:flex [&_span]:items-center [&_span]:gap-2",
  "studio-contract": "sticky top-4 h-fit rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-5 max-[64rem]:static [&_h2]:mt-4 [&_h2]:text-[color:var(--ink)] [&_li]:flex [&_li]:items-center [&_li]:gap-[0.7rem] [&_li]:text-[0.9rem] [&_li]:leading-[1.45] [&_li]:text-[color:var(--ink-soft)] [&_li_span]:text-[0.72rem] [&_li_span]:font-black [&_li_span]:tracking-[0.08em] [&_li_span]:text-[color:var(--terracotta-dark)] [&_ol]:mt-4 [&_ol]:grid [&_ol]:list-none [&_ol]:gap-[0.7rem] [&_ol]:p-0 [&_svg]:text-[color:var(--terracotta-dark)]",

  "admin-resource": "mx-auto max-w-[82rem]",
  "admin-resource-hero": "flex items-end justify-between gap-8 rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-[clamp(1.5rem,3vw,2.5rem)] max-[44rem]:flex-col max-[44rem]:items-start [&_h1]:mt-[0.45rem] [&_h1]:max-w-[48rem] [&_h1]:text-[clamp(2.3rem,5vw,5.1rem)] [&_h1]:leading-[0.98] [&_p:not(.admin-eyebrow)]:mt-4 [&_p:not(.admin-eyebrow)]:max-w-[42rem] [&_p:not(.admin-eyebrow)]:leading-[1.7] [&_p:not(.admin-eyebrow)]:text-[color:var(--ink-soft)]",
  "admin-resource-layout": "mt-4 grid grid-cols-[minmax(22rem,0.42fr)_minmax(0,1fr)] gap-4 max-[72rem]:grid-cols-1",
  "admin-resource-list": "max-h-[48rem] overflow-auto rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-3",
  "admin-resource-detail": "min-w-0 rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-4",
  "admin-resource-list-item": "grid w-full gap-[0.45rem] rounded-[var(--radius-sm)] border border-transparent bg-transparent p-4 text-left text-[color:var(--ink)] transition-[background-color,border-color] duration-[180ms] hover:border-[var(--line)] hover:bg-[color-mix(in_srgb,var(--paper)_75%,white)] data-[active=true]:border-[color-mix(in_srgb,var(--terracotta-dark)_42%,var(--line))] data-[active=true]:bg-[color-mix(in_srgb,var(--terracotta)_10%,var(--paper-raised))] [&+&]:mt-[0.45rem] [&_b]:block [&_small]:block [&_small]:text-[color:var(--ink-soft)] [&_strong]:block",
  "admin-resource-list-meta": "flex justify-between gap-3 text-[0.8rem] font-extrabold text-[color:var(--terracotta-dark)] [&_small]:text-[color:var(--ink-soft)]",
  "admin-list-stack": "mt-[0.45rem]",
  "admin-detail-card": "rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)] p-[clamp(1rem,2vw,1.5rem)]",
  "admin-detail-head": "flex items-start justify-between gap-4 [&_h2]:mt-[0.35rem] [&_h2]:line-clamp-4 [&_h2]:overflow-hidden [&_h2]:text-[clamp(1.55rem,2vw,2.25rem)] [&_h2]:leading-[1.05] [&_h2]:tracking-[-0.03em] [&_h2]:text-[color:var(--ink)] [&_p]:mt-[0.4rem] [&_p]:text-[color:var(--ink-soft)]",
  "admin-action-row": "flex flex-wrap gap-[0.55rem]",
  "admin-action-grid": "mt-[0.8rem] flex flex-wrap gap-[0.55rem]",
  "admin-secondary-action": "inline-flex min-h-[2.65rem] items-center justify-center gap-[0.45rem] rounded-[var(--radius-sm)] border border-[var(--line)] bg-[var(--paper)] px-[0.85rem] text-[0.85rem] font-extrabold text-[color:var(--ink)] disabled:cursor-not-allowed disabled:opacity-60",
  "admin-danger-action": "inline-flex min-h-[2.65rem] items-center justify-center gap-[0.45rem] rounded-[var(--radius-sm)] border border-[color-mix(in_srgb,#b42318_28%,var(--line))] bg-[color-mix(in_srgb,#fddbd6_58%,var(--paper))] px-[0.85rem] text-[0.85rem] font-extrabold text-[#8f1d14] disabled:cursor-not-allowed disabled:opacity-60",
  "admin-stat-grid": "mt-5 grid grid-cols-5 gap-[0.55rem] max-[72rem]:grid-cols-2 max-[44rem]:grid-cols-1 [&_div]:rounded-[var(--radius-sm)] [&_div]:border [&_div]:border-[var(--line)] [&_div]:bg-[var(--paper)] [&_div]:p-[0.8rem] [&_p]:m-0 [&_p]:text-[0.78rem] [&_p]:font-extrabold [&_p]:text-[color:var(--ink-soft)] [&_strong]:mt-[0.35rem] [&_strong]:block [&_strong]:text-2xl [&_strong]:text-[color:var(--ink)]",
  "admin-table-wrap": "mt-4 overflow-x-auto rounded-[var(--radius-sm)] border border-[var(--line)] bg-[var(--paper)]",
  "admin-table": "w-full min-w-[52rem] border-collapse text-left text-[color:var(--ink)] [&_td]:border-b [&_td]:border-[var(--line)] [&_td]:p-[0.8rem] [&_td]:align-top [&_th]:border-b [&_th]:border-[var(--line)] [&_th]:p-[0.8rem] [&_th]:text-[0.75rem] [&_th]:font-black [&_th]:text-[color:var(--ink-soft)] [&_th]:uppercase",
  "admin-empty": "p-4 text-[color:var(--ink-soft)]",
  "admin-field": "min-h-[2.85rem] w-full rounded-[var(--radius-sm)] border border-[var(--line)] bg-[var(--paper)] px-[0.85rem] text-[color:var(--ink)] outline-none",
  "admin-textarea": "min-h-36 py-[0.8rem]",
  "admin-code-field": "min-h-[22rem] font-mono",
  "admin-form-stack": "grid gap-[0.8rem] [&_label]:grid [&_label]:gap-[0.45rem] [&_label]:text-[0.82rem] [&_label]:font-extrabold [&_label]:text-[color:var(--ink)]",
  "admin-inline-form": "mt-4 grid grid-cols-4 gap-3 max-[72rem]:grid-cols-2 max-[44rem]:grid-cols-1 [&_label]:grid [&_label]:gap-[0.45rem] [&_label]:text-[0.82rem] [&_label]:font-extrabold [&_label]:text-[color:var(--ink)]",
  "admin-template-form": "mt-4 grid grid-cols-4 gap-3 max-[72rem]:grid-cols-1 [&_label]:grid [&_label]:gap-[0.45rem] [&_label]:text-[0.82rem] [&_label]:font-extrabold [&_label]:text-[color:var(--ink)]",
  "admin-check": "!flex !grid-cols-none items-center",
  "admin-status-pill": "rounded-full bg-[color-mix(in_srgb,var(--terracotta)_12%,var(--paper-raised))] px-[0.7rem] py-[0.35rem] text-[0.76rem] font-black text-[color:var(--terracotta-dark)]",
  "admin-gallery-list": "max-h-[54rem]",
  "admin-gallery-item": "relative grid min-h-[6.5rem] grid-cols-[4.75rem_minmax(0,1fr)] items-center pr-20 max-[44rem]:grid-cols-1 [&_b]:absolute [&_b]:right-4 [&_b]:top-4 [&_b]:rounded-full [&_b]:bg-[color-mix(in_srgb,var(--terracotta)_12%,var(--paper-raised))] [&_b]:px-[0.62rem] [&_b]:py-[0.32rem] [&_b]:text-[0.72rem] [&_b]:font-black [&_b]:text-[color:var(--terracotta-dark)] [&_small]:mt-[0.3rem] [&_strong]:line-clamp-2 [&_strong]:overflow-hidden [&_strong]:leading-[1.2]",
  "admin-square-preview": "relative block aspect-square overflow-hidden rounded-[var(--radius-sm)] bg-[var(--paper)] [&_img]:h-full [&_img]:w-full [&_img]:object-cover",
  "admin-gallery-detail": "grid grid-cols-[minmax(0,1fr)_minmax(18rem,0.36fr)] gap-4 max-[72rem]:grid-cols-1",
  "admin-danger-zone": "mt-4 border-t border-[var(--line)] pt-4 [&_p]:mb-[0.6rem] [&_p]:mt-0 [&_p]:text-[0.78rem] [&_p]:font-black [&_p]:text-[#8f1d14] [&_p]:uppercase",
  "admin-template-grid": "mt-4 grid grid-cols-3 gap-4 max-[72rem]:grid-cols-2 max-[44rem]:grid-cols-1",
  "admin-template-card": "overflow-hidden rounded-[var(--radius-md)] border border-[var(--line)] bg-[color-mix(in_srgb,var(--paper-raised)_88%,white)]",
  "admin-portrait-preview": "relative aspect-[3/4] overflow-hidden bg-[var(--paper)]",
  "admin-template-body": "p-4 [&_p]:mt-[0.4rem] [&_p]:text-[color:var(--ink-soft)]",
};

export function adminClass(tokens: string, extra?: string) {
  return cn(tokens, ...tokens.split(/\s+/).map((token) => adminStyles[token]), extra);
}
